spring:
  application:
    name: hotel-management
  
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=QuanLyKhachSanDb;encrypt=false
    username: sa
    password: 123456
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
        format_sql: true
  
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    mode: HTML
  
  web:
    resources:
      static-locations: classpath:/static/
  
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 8080
  servlet:
    context-path: /

logging:
  level:
    com.dealer.hotel: DEBUG
    org.springframework.security: DEBUG